'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.42000
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace FelWebService
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaTFD33", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaTFD33
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoConfirmacionField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoRespuestaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CreditosRestantesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorDetalladoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperacionExitosaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PDFResultadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimbreField As FelWebService.Timbre33
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XMLResultadoField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoConfirmacion() As String
            Get
                Return Me.CodigoConfirmacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoConfirmacionField, value) <> true) Then
                    Me.CodigoConfirmacionField = value
                    Me.RaisePropertyChanged("CodigoConfirmacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoRespuesta() As String
            Get
                Return Me.CodigoRespuestaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoRespuestaField, value) <> true) Then
                    Me.CodigoRespuestaField = value
                    Me.RaisePropertyChanged("CodigoRespuesta")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CreditosRestantes() As Integer
            Get
                Return Me.CreditosRestantesField
            End Get
            Set
                If (Me.CreditosRestantesField.Equals(value) <> true) Then
                    Me.CreditosRestantesField = value
                    Me.RaisePropertyChanged("CreditosRestantes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeError() As String
            Get
                Return Me.MensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorField, value) <> true) Then
                    Me.MensajeErrorField = value
                    Me.RaisePropertyChanged("MensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeErrorDetallado() As String
            Get
                Return Me.MensajeErrorDetalladoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorDetalladoField, value) <> true) Then
                    Me.MensajeErrorDetalladoField = value
                    Me.RaisePropertyChanged("MensajeErrorDetallado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.OperacionExitosaField
            End Get
            Set
                If (Me.OperacionExitosaField.Equals(value) <> true) Then
                    Me.OperacionExitosaField = value
                    Me.RaisePropertyChanged("OperacionExitosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property PDFResultado() As String
            Get
                Return Me.PDFResultadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PDFResultadoField, value) <> true) Then
                    Me.PDFResultadoField = value
                    Me.RaisePropertyChanged("PDFResultado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Timbre() As FelWebService.Timbre33
            Get
                Return Me.TimbreField
            End Get
            Set
                If (Object.ReferenceEquals(Me.TimbreField, value) <> true) Then
                    Me.TimbreField = value
                    Me.RaisePropertyChanged("Timbre")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XMLResultado() As String
            Get
                Return Me.XMLResultadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XMLResultadoField, value) <> true) Then
                    Me.XMLResultadoField = value
                    Me.RaisePropertyChanged("XMLResultado")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="Timbre33", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class Timbre33
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaTimbradoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NumeroCertificadoSATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SelloCFDField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private SelloSATField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UUIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As String
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoField, value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaTimbrado() As Date
            Get
                Return Me.FechaTimbradoField
            End Get
            Set
                If (Me.FechaTimbradoField.Equals(value) <> true) Then
                    Me.FechaTimbradoField = value
                    Me.RaisePropertyChanged("FechaTimbrado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NumeroCertificadoSAT() As String
            Get
                Return Me.NumeroCertificadoSATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NumeroCertificadoSATField, value) <> true) Then
                    Me.NumeroCertificadoSATField = value
                    Me.RaisePropertyChanged("NumeroCertificadoSAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SelloCFD() As String
            Get
                Return Me.SelloCFDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SelloCFDField, value) <> true) Then
                    Me.SelloCFDField = value
                    Me.RaisePropertyChanged("SelloCFD")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property SelloSAT() As String
            Get
                Return Me.SelloSATField
            End Get
            Set
                If (Object.ReferenceEquals(Me.SelloSATField, value) <> true) Then
                    Me.SelloSATField = value
                    Me.RaisePropertyChanged("SelloSAT")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.UUIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UUIDField, value) <> true) Then
                    Me.UUIDField = value
                    Me.RaisePropertyChanged("UUID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaCancelacion", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaCancelacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DetallesCancelacionField() As FelWebService.DetalleCancelacion
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorDetalladoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperacionExitosaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XMLAcuseField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DetallesCancelacion() As FelWebService.DetalleCancelacion()
            Get
                Return Me.DetallesCancelacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DetallesCancelacionField, value) <> true) Then
                    Me.DetallesCancelacionField = value
                    Me.RaisePropertyChanged("DetallesCancelacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeError() As String
            Get
                Return Me.MensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorField, value) <> true) Then
                    Me.MensajeErrorField = value
                    Me.RaisePropertyChanged("MensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeErrorDetallado() As String
            Get
                Return Me.MensajeErrorDetalladoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorDetalladoField, value) <> true) Then
                    Me.MensajeErrorDetalladoField = value
                    Me.RaisePropertyChanged("MensajeErrorDetallado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.OperacionExitosaField
            End Get
            Set
                If (Me.OperacionExitosaField.Equals(value) <> true) Then
                    Me.OperacionExitosaField = value
                    Me.RaisePropertyChanged("OperacionExitosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XMLAcuse() As String
            Get
                Return Me.XMLAcuseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XMLAcuseField, value) <> true) Then
                    Me.XMLAcuseField = value
                    Me.RaisePropertyChanged("XMLAcuse")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DetalleCancelacion", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DetalleCancelacion
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private CodigoResultadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeResultadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UUIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property CodigoResultado() As String
            Get
                Return Me.CodigoResultadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.CodigoResultadoField, value) <> true) Then
                    Me.CodigoResultadoField = value
                    Me.RaisePropertyChanged("CodigoResultado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeResultado() As String
            Get
                Return Me.MensajeResultadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeResultadoField, value) <> true) Then
                    Me.MensajeResultadoField = value
                    Me.RaisePropertyChanged("MensajeResultado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.UUIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UUIDField, value) <> true) Then
                    Me.UUIDField = value
                    Me.RaisePropertyChanged("UUID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaCancelacionAsincrona", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaCancelacionAsincrona
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private DetallesCancelacionField() As FelWebService.DetalleCancelacion
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperacionExitosaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenciaField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property DetallesCancelacion() As FelWebService.DetalleCancelacion()
            Get
                Return Me.DetallesCancelacionField
            End Get
            Set
                If (Object.ReferenceEquals(Me.DetallesCancelacionField, value) <> true) Then
                    Me.DetallesCancelacionField = value
                    Me.RaisePropertyChanged("DetallesCancelacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeError() As String
            Get
                Return Me.MensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorField, value) <> true) Then
                    Me.MensajeErrorField = value
                    Me.RaisePropertyChanged("MensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.OperacionExitosaField
            End Get
            Set
                If (Me.OperacionExitosaField.Equals(value) <> true) Then
                    Me.OperacionExitosaField = value
                    Me.RaisePropertyChanged("OperacionExitosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Referencia() As String
            Get
                Return Me.ReferenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenciaField, value) <> true) Then
                    Me.ReferenciaField = value
                    Me.RaisePropertyChanged("Referencia")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaEstatusCancelacionAsincrona", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaEstatusCancelacionAsincrona
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstatusField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperacionExitosaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ReferenciaField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private XMLAcuseField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estatus() As String
            Get
                Return Me.EstatusField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstatusField, value) <> true) Then
                    Me.EstatusField = value
                    Me.RaisePropertyChanged("Estatus")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeError() As String
            Get
                Return Me.MensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorField, value) <> true) Then
                    Me.MensajeErrorField = value
                    Me.RaisePropertyChanged("MensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.OperacionExitosaField
            End Get
            Set
                If (Me.OperacionExitosaField.Equals(value) <> true) Then
                    Me.OperacionExitosaField = value
                    Me.RaisePropertyChanged("OperacionExitosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Referencia() As String
            Get
                Return Me.ReferenciaField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ReferenciaField, value) <> true) Then
                    Me.ReferenciaField = value
                    Me.RaisePropertyChanged("Referencia")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property XMLAcuse() As String
            Get
                Return Me.XMLAcuseField
            End Get
            Set
                If (Object.ReferenceEquals(Me.XMLAcuseField, value) <> true) Then
                    Me.XMLAcuseField = value
                    Me.RaisePropertyChanged("XMLAcuse")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaCreditos", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaCreditos
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperacionExitosaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaquetesField() As FelWebService.DetallesPaqueteCreditos
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeError() As String
            Get
                Return Me.MensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorField, value) <> true) Then
                    Me.MensajeErrorField = value
                    Me.RaisePropertyChanged("MensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.OperacionExitosaField
            End Get
            Set
                If (Me.OperacionExitosaField.Equals(value) <> true) Then
                    Me.OperacionExitosaField = value
                    Me.RaisePropertyChanged("OperacionExitosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Paquetes() As FelWebService.DetallesPaqueteCreditos()
            Get
                Return Me.PaquetesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaquetesField, value) <> true) Then
                    Me.PaquetesField = value
                    Me.RaisePropertyChanged("Paquetes")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="DetallesPaqueteCreditos", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class DetallesPaqueteCreditos
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EnUsoField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaActivacionField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaVencimientoField As System.Nullable(Of Date)
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private PaqueteField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimbresField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimbresRestantesField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TimbresUsadosField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private VigenteField As Boolean
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property EnUso() As Boolean
            Get
                Return Me.EnUsoField
            End Get
            Set
                If (Me.EnUsoField.Equals(value) <> true) Then
                    Me.EnUsoField = value
                    Me.RaisePropertyChanged("EnUso")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaActivacion() As System.Nullable(Of Date)
            Get
                Return Me.FechaActivacionField
            End Get
            Set
                If (Me.FechaActivacionField.Equals(value) <> true) Then
                    Me.FechaActivacionField = value
                    Me.RaisePropertyChanged("FechaActivacion")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaVencimiento() As System.Nullable(Of Date)
            Get
                Return Me.FechaVencimientoField
            End Get
            Set
                If (Me.FechaVencimientoField.Equals(value) <> true) Then
                    Me.FechaVencimientoField = value
                    Me.RaisePropertyChanged("FechaVencimiento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Paquete() As String
            Get
                Return Me.PaqueteField
            End Get
            Set
                If (Object.ReferenceEquals(Me.PaqueteField, value) <> true) Then
                    Me.PaqueteField = value
                    Me.RaisePropertyChanged("Paquete")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Timbres() As Integer
            Get
                Return Me.TimbresField
            End Get
            Set
                If (Me.TimbresField.Equals(value) <> true) Then
                    Me.TimbresField = value
                    Me.RaisePropertyChanged("Timbres")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimbresRestantes() As Integer
            Get
                Return Me.TimbresRestantesField
            End Get
            Set
                If (Me.TimbresRestantesField.Equals(value) <> true) Then
                    Me.TimbresRestantesField = value
                    Me.RaisePropertyChanged("TimbresRestantes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TimbresUsados() As Integer
            Get
                Return Me.TimbresUsadosField
            End Get
            Set
                If (Me.TimbresUsadosField.Equals(value) <> true) Then
                    Me.TimbresUsadosField = value
                    Me.RaisePropertyChanged("TimbresUsados")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Vigente() As Boolean
            Get
                Return Me.VigenteField
            End Get
            Set
                If (Me.VigenteField.Equals(value) <> true) Then
                    Me.VigenteField = value
                    Me.RaisePropertyChanged("Vigente")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RespuestaReporte", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RespuestaReporte
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private ListaComprobantesField() As FelWebService.RegistroTimbre
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private MensajeErrorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private OperacionExitosaField As Boolean
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private TotalComprobantesPeriodoField As Integer
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property ListaComprobantes() As FelWebService.RegistroTimbre()
            Get
                Return Me.ListaComprobantesField
            End Get
            Set
                If (Object.ReferenceEquals(Me.ListaComprobantesField, value) <> true) Then
                    Me.ListaComprobantesField = value
                    Me.RaisePropertyChanged("ListaComprobantes")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property MensajeError() As String
            Get
                Return Me.MensajeErrorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.MensajeErrorField, value) <> true) Then
                    Me.MensajeErrorField = value
                    Me.RaisePropertyChanged("MensajeError")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property OperacionExitosa() As Boolean
            Get
                Return Me.OperacionExitosaField
            End Get
            Set
                If (Me.OperacionExitosaField.Equals(value) <> true) Then
                    Me.OperacionExitosaField = value
                    Me.RaisePropertyChanged("OperacionExitosa")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property TotalComprobantesPeriodo() As Integer
            Get
                Return Me.TotalComprobantesPeriodoField
            End Get
            Set
                If (Me.TotalComprobantesPeriodoField.Equals(value) <> true) Then
                    Me.TotalComprobantesPeriodoField = value
                    Me.RaisePropertyChanged("TotalComprobantesPeriodo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="RegistroTimbre", [Namespace]:="http://schemas.datacontract.org/2004/07/TES.TFD.V33.Negocios"),  _
     System.SerializableAttribute()>  _
    Partial Public Class RegistroTimbre
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private EstadoField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private FechaTimbradoField As Date
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NoFilaField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RFCEmisorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private RFCReceptorField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private UUIDField As String
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property Estado() As String
            Get
                Return Me.EstadoField
            End Get
            Set
                If (Object.ReferenceEquals(Me.EstadoField, value) <> true) Then
                    Me.EstadoField = value
                    Me.RaisePropertyChanged("Estado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property FechaTimbrado() As Date
            Get
                Return Me.FechaTimbradoField
            End Get
            Set
                If (Me.FechaTimbradoField.Equals(value) <> true) Then
                    Me.FechaTimbradoField = value
                    Me.RaisePropertyChanged("FechaTimbrado")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property NoFila() As Integer
            Get
                Return Me.NoFilaField
            End Get
            Set
                If (Me.NoFilaField.Equals(value) <> true) Then
                    Me.NoFilaField = value
                    Me.RaisePropertyChanged("NoFila")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RFCEmisor() As String
            Get
                Return Me.RFCEmisorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RFCEmisorField, value) <> true) Then
                    Me.RFCEmisorField = value
                    Me.RaisePropertyChanged("RFCEmisor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property RFCReceptor() As String
            Get
                Return Me.RFCReceptorField
            End Get
            Set
                If (Object.ReferenceEquals(Me.RFCReceptorField, value) <> true) Then
                    Me.RFCReceptorField = value
                    Me.RaisePropertyChanged("RFCReceptor")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute()>  _
        Public Property UUID() As String
            Get
                Return Me.UUIDField
            End Get
            Set
                If (Object.ReferenceEquals(Me.UUIDField, value) <> true) Then
                    Me.UUIDField = value
                    Me.RaisePropertyChanged("UUID")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="FelWebService.IWSCFDI33")>  _
    Public Interface IWSCFDI33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/TimbrarCFDI", ReplyAction:="http://tempuri.org/IWSCFDI33/TimbrarCFDIResponse")>  _
        Function TimbrarCFDI(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/TimbrarCFDI", ReplyAction:="http://tempuri.org/IWSCFDI33/TimbrarCFDIResponse")>  _
        Function TimbrarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/CancelarCFDI", ReplyAction:="http://tempuri.org/IWSCFDI33/CancelarCFDIResponse")>  _
        Function CancelarCFDI(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As FelWebService.RespuestaCancelacion
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/CancelarCFDI", ReplyAction:="http://tempuri.org/IWSCFDI33/CancelarCFDIResponse")>  _
        Function CancelarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaCancelacion)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/CancelacionAsincrona", ReplyAction:="http://tempuri.org/IWSCFDI33/CancelacionAsincronaResponse")>  _
        Function CancelacionAsincrona(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As FelWebService.RespuestaCancelacionAsincrona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/CancelacionAsincrona", ReplyAction:="http://tempuri.org/IWSCFDI33/CancelacionAsincronaResponse")>  _
        Function CancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaCancelacionAsincrona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincrona", ReplyAction:="http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincronaResponse")>  _
        Function EstatusCancelacionAsincrona(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As FelWebService.RespuestaEstatusCancelacionAsincrona
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincrona", ReplyAction:="http://tempuri.org/IWSCFDI33/EstatusCancelacionAsincronaResponse")>  _
        Function EstatusCancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaEstatusCancelacionAsincrona)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ObtenerPDF", ReplyAction:="http://tempuri.org/IWSCFDI33/ObtenerPDFResponse")>  _
        Function ObtenerPDF(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal LogoBase64 As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ObtenerPDF", ReplyAction:="http://tempuri.org/IWSCFDI33/ObtenerPDFResponse")>  _
        Function ObtenerPDFAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal LogoBase64 As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvio", ReplyAction:="http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvioResponse")>  _
        Function ObtenerAcuseEnvio(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvio", ReplyAction:="http://tempuri.org/IWSCFDI33/ObtenerAcuseEnvioResponse")>  _
        Function ObtenerAcuseEnvioAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacion", ReplyAction:="http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacionResponse")>  _
        Function ObtenerAcuseCancelacion(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacion", ReplyAction:="http://tempuri.org/IWSCFDI33/ObtenerAcuseCancelacionResponse")>  _
        Function ObtenerAcuseCancelacionAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/CambiarPassword", ReplyAction:="http://tempuri.org/IWSCFDI33/CambiarPasswordResponse")>  _
        Function CambiarPassword(ByVal usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/CambiarPassword", ReplyAction:="http://tempuri.org/IWSCFDI33/CambiarPasswordResponse")>  _
        Function CambiarPasswordAsync(ByVal usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbre", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbreResponse")>  _
        Function ConsultarComplementoTimbre(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbre", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarComplementoTimbreResponse")>  _
        Function ConsultarComplementoTimbreAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferencia", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferenciaResponse")>  _
        Function ConsultarTimbrePorReferencia(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As FelWebService.RespuestaTFD33
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferencia", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarTimbrePorReferenciaResponse")>  _
        Function ConsultarTimbrePorReferenciaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarCreditos", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarCreditosResponse")>  _
        Function ConsultarCreditos(ByVal usuario As String, ByVal password As String) As FelWebService.RespuestaCreditos
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarCreditos", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarCreditosResponse")>  _
        Function ConsultarCreditosAsync(ByVal usuario As String, ByVal password As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaCreditos)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarComprobantes", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarComprobantesResponse")>  _
        Function ConsultarComprobantes(ByVal usuario As String, ByVal password As String, ByVal fechaInicial As Date, ByVal fechaFinal As Date, ByVal filaInicial As Integer) As FelWebService.RespuestaReporte
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/IWSCFDI33/ConsultarComprobantes", ReplyAction:="http://tempuri.org/IWSCFDI33/ConsultarComprobantesResponse")>  _
        Function ConsultarComprobantesAsync(ByVal usuario As String, ByVal password As String, ByVal fechaInicial As Date, ByVal fechaFinal As Date, ByVal filaInicial As Integer) As System.Threading.Tasks.Task(Of FelWebService.RespuestaReporte)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface IWSCFDI33Channel
        Inherits FelWebService.IWSCFDI33, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class WSCFDI33Client
        Inherits System.ServiceModel.ClientBase(Of FelWebService.IWSCFDI33)
        Implements FelWebService.IWSCFDI33
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function TimbrarCFDI(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.TimbrarCFDI
            Return MyBase.Channel.TimbrarCFDI(usuario, password, cadenaXML, referencia)
        End Function
        
        Public Function TimbrarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal cadenaXML As String, ByVal referencia As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.TimbrarCFDIAsync
            Return MyBase.Channel.TimbrarCFDIAsync(usuario, password, cadenaXML, referencia)
        End Function
        
        Public Function CancelarCFDI(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As FelWebService.RespuestaCancelacion Implements FelWebService.IWSCFDI33.CancelarCFDI
            Return MyBase.Channel.CancelarCFDI(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada)
        End Function
        
        Public Function CancelarCFDIAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaCancelacion) Implements FelWebService.IWSCFDI33.CancelarCFDIAsync
            Return MyBase.Channel.CancelarCFDIAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada)
        End Function
        
        Public Function CancelacionAsincrona(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As FelWebService.RespuestaCancelacionAsincrona Implements FelWebService.IWSCFDI33.CancelacionAsincrona
            Return MyBase.Channel.CancelacionAsincrona(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada)
        End Function
        
        Public Function CancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal rFCEmisor As String, ByVal listaCFDI() As String, ByVal clavePrivada_Base64 As String, ByVal passwordClavePrivada As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaCancelacionAsincrona) Implements FelWebService.IWSCFDI33.CancelacionAsincronaAsync
            Return MyBase.Channel.CancelacionAsincronaAsync(usuario, password, rFCEmisor, listaCFDI, clavePrivada_Base64, passwordClavePrivada)
        End Function
        
        Public Function EstatusCancelacionAsincrona(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As FelWebService.RespuestaEstatusCancelacionAsincrona Implements FelWebService.IWSCFDI33.EstatusCancelacionAsincrona
            Return MyBase.Channel.EstatusCancelacionAsincrona(usuario, password, referencia)
        End Function
        
        Public Function EstatusCancelacionAsincronaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaEstatusCancelacionAsincrona) Implements FelWebService.IWSCFDI33.EstatusCancelacionAsincronaAsync
            Return MyBase.Channel.EstatusCancelacionAsincronaAsync(usuario, password, referencia)
        End Function
        
        Public Function ObtenerPDF(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal LogoBase64 As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.ObtenerPDF
            Return MyBase.Channel.ObtenerPDF(usuario, password, uUID, LogoBase64)
        End Function
        
        Public Function ObtenerPDFAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String, ByVal LogoBase64 As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.ObtenerPDFAsync
            Return MyBase.Channel.ObtenerPDFAsync(usuario, password, uUID, LogoBase64)
        End Function
        
        Public Function ObtenerAcuseEnvio(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.ObtenerAcuseEnvio
            Return MyBase.Channel.ObtenerAcuseEnvio(usuario, password, uUID)
        End Function
        
        Public Function ObtenerAcuseEnvioAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.ObtenerAcuseEnvioAsync
            Return MyBase.Channel.ObtenerAcuseEnvioAsync(usuario, password, uUID)
        End Function
        
        Public Function ObtenerAcuseCancelacion(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.ObtenerAcuseCancelacion
            Return MyBase.Channel.ObtenerAcuseCancelacion(usuario, password, uUID)
        End Function
        
        Public Function ObtenerAcuseCancelacionAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.ObtenerAcuseCancelacionAsync
            Return MyBase.Channel.ObtenerAcuseCancelacionAsync(usuario, password, uUID)
        End Function
        
        Public Function CambiarPassword(ByVal usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.CambiarPassword
            Return MyBase.Channel.CambiarPassword(usuario, passwordActual, passwordNuevo)
        End Function
        
        Public Function CambiarPasswordAsync(ByVal usuario As String, ByVal passwordActual As String, ByVal passwordNuevo As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.CambiarPasswordAsync
            Return MyBase.Channel.CambiarPasswordAsync(usuario, passwordActual, passwordNuevo)
        End Function
        
        Public Function ConsultarComplementoTimbre(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.ConsultarComplementoTimbre
            Return MyBase.Channel.ConsultarComplementoTimbre(usuario, password, uUID)
        End Function
        
        Public Function ConsultarComplementoTimbreAsync(ByVal usuario As String, ByVal password As String, ByVal uUID As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.ConsultarComplementoTimbreAsync
            Return MyBase.Channel.ConsultarComplementoTimbreAsync(usuario, password, uUID)
        End Function
        
        Public Function ConsultarTimbrePorReferencia(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As FelWebService.RespuestaTFD33 Implements FelWebService.IWSCFDI33.ConsultarTimbrePorReferencia
            Return MyBase.Channel.ConsultarTimbrePorReferencia(usuario, password, referencia)
        End Function
        
        Public Function ConsultarTimbrePorReferenciaAsync(ByVal usuario As String, ByVal password As String, ByVal referencia As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaTFD33) Implements FelWebService.IWSCFDI33.ConsultarTimbrePorReferenciaAsync
            Return MyBase.Channel.ConsultarTimbrePorReferenciaAsync(usuario, password, referencia)
        End Function
        
        Public Function ConsultarCreditos(ByVal usuario As String, ByVal password As String) As FelWebService.RespuestaCreditos Implements FelWebService.IWSCFDI33.ConsultarCreditos
            Return MyBase.Channel.ConsultarCreditos(usuario, password)
        End Function
        
        Public Function ConsultarCreditosAsync(ByVal usuario As String, ByVal password As String) As System.Threading.Tasks.Task(Of FelWebService.RespuestaCreditos) Implements FelWebService.IWSCFDI33.ConsultarCreditosAsync
            Return MyBase.Channel.ConsultarCreditosAsync(usuario, password)
        End Function
        
        Public Function ConsultarComprobantes(ByVal usuario As String, ByVal password As String, ByVal fechaInicial As Date, ByVal fechaFinal As Date, ByVal filaInicial As Integer) As FelWebService.RespuestaReporte Implements FelWebService.IWSCFDI33.ConsultarComprobantes
            Return MyBase.Channel.ConsultarComprobantes(usuario, password, fechaInicial, fechaFinal, filaInicial)
        End Function
        
        Public Function ConsultarComprobantesAsync(ByVal usuario As String, ByVal password As String, ByVal fechaInicial As Date, ByVal fechaFinal As Date, ByVal filaInicial As Integer) As System.Threading.Tasks.Task(Of FelWebService.RespuestaReporte) Implements FelWebService.IWSCFDI33.ConsultarComprobantesAsync
            Return MyBase.Channel.ConsultarComprobantesAsync(usuario, password, fechaInicial, fechaFinal, filaInicial)
        End Function
    End Class
End Namespace
